AWSTemplateFormatVersion: "2010-09-09"
Description: "PayID Lambda Server and API Gateway front end"

Parameters:
  lambdaFunctionName:
    Type: "String"
    AllowedPattern: "^[a-zA-Z0-9]+[a-zA-Z0-9-]+[a-zA-Z0-9]+$"
    Default: "payid-server"

  domainName:
    Type: "String"
    AllowedPattern: "^[a-z0-9.]+$"
    Description: "A domain that you can manage which you want your Pay IDs to be hosted at."

  certificateArn:
    Type: "String"
    Description: "Needs to be the ARN of a certificate in Amazon Certificate Manager in us-east-1."

Resources:
  apiGateway:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: "payid-server-api"
      Description: "API Gateway endpoints to invoke PayID Lambda"

  apiGatewayPayIdResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref apiGateway
      ParentId: !GetAtt
        - apiGateway
        - RootResourceId
      PathPart: "{payId}"

  apiGatewayRootMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      AuthorizationType: "NONE"
      HttpMethod: "GET"
      Integration:
        IntegrationHttpMethod: "POST"
        Type: "AWS_PROXY"
        Uri: !Sub
          - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations"
          - lambdaArn: !GetAtt "lambdaFunction.Arn"
      ResourceId: !GetAtt "apiGateway.RootResourceId"
      RestApiId: !Ref "apiGateway"

  apiGatewayPayIdMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      AuthorizationType: "NONE"
      HttpMethod: "GET"
      Integration:
        IntegrationHttpMethod: "POST"
        Type: "AWS_PROXY"
        Uri: !Sub
          - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations"
          - lambdaArn: !GetAtt "lambdaFunction.Arn"
      ResourceId: !Ref "apiGatewayPayIdResource"
      RestApiId: !Ref "apiGateway"

  apiGatewayDeployment:
    Type: "AWS::ApiGateway::Deployment"
    DependsOn:
      - "apiGatewayRootMethod"
    Properties:
      RestApiId: !Ref "apiGateway"
      StageName: "release"

  apiGatewayCustomDomain:
    Type: "AWS::ApiGateway::DomainName"
    Properties:
      CertificateArn: !Ref "certificateArn"
      DomainName: !Ref "domainName"
      SecurityPolicy: "TLS_1_2"

  apiGatewayDomainResourceMapping:
    Type: "AWS::ApiGateway::BasePathMapping"
    DependsOn: "apiGatewayDeployment"
    Properties:
      DomainName: !Ref "domainName"
      RestApiId: !Ref "apiGateway"
      Stage: "release"

  s3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  writeTestAccountToS3Fn:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        ZipFile: |
          const AWS = require('aws-sdk');
          const response = require('cfn-response');

          const s3 = new AWS.S3();

          exports.handler =  function(event, context) {

              const testAccount = {
                  addresses: [
                      {
                          paymentNetwork: "XRPL",
                          environment: "TESTNET",
                          addressDetailsType: "CryptoAddressDetails",
                          addressDetails: {
                              address: "T772A73My52QaUonaai6VE4X98zLu7VBQSXJKLYimjXDAJi"
                          }
                      }
                  ],
                  payId: `testaccount$${process.env.PAYID_DOMAIN}`
              };

                  const params = {
                      Bucket: process.env.PAYID_BUCKET,
                      Key: 'testaccount.json',
                      Body: JSON.stringify(testAccount),
                      ContentType: "application/json"
                  };

                  console.log('creating test account');
                  s3.putObject(params).promise().then(() => {
                      console.log('test account created');
                      response.send(event, context, response.SUCCESS, {});
                  }).catch((error) => {
                      console.log(error);
                      response.send(event, context, response.FAILURE, {});
                  });
          };
      Description: "PayID Test Account Generator"
      Environment:
        Variables:
          PAYID_BUCKET: !Ref "s3Bucket"
          PAYID_DOMAIN: !Ref "domainName"
      Handler: "index.handler"
      MemorySize: 128
      Role: !GetAtt "lambdaIAMRole.Arn"
      Runtime: "nodejs12.x"
      Timeout: 10

  writeTestAccountToS3:
    Type: "Custom::writeTestAccountToS3Fn"
    Properties:
      ServiceToken: !GetAtt "writeTestAccountToS3Fn.Arn"

  lambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        ZipFile: |
          const AWS = require('aws-sdk');

          const s3 = new AWS.S3();

          const networkHeaders = [
              'application/xrpl-testnet+json',
              'application/xrpl-mainnet+json',
          ];

          const responseHeaders = {
              'Access-Control-Allow-Origin': '*',
              'Access-Control-Allow-Methods': 'POST, GET, OPTIONS',
              'Access-Control-Allow-Headers': 'PayID-Version',
              'Access-Control-Expose-Headers': 'PayID-Version, PayID-Server-Version',
              'Cache-Control': 'no-store',
          };

          const success = {
              statusCode: 200,
              headers: responseHeaders,
          };

          exports.handler =  async function(event, context) {
              if (event.path === '/') {
                  return { ...success, body: 'Welcome to PayID!' };
              }

              const payIdVersionHeader = event.headers['PayID-Version'];
              if (payIdVersionHeader && payIdVersionHeader !== '1.0') {
                  return {
                      statusCode: 422,
                      body: 'Unknown PayID version set.',
                  };
              }

              const payId = event.pathParameters.payId;
              try {
                  const params = {
                      Bucket: process.env.PAYID_BUCKET,
                      Key: `${payId}.json`,
                  };
                  const payIdResource = await s3.getObject(params).promise();

                  const payIdJson = JSON.parse(payIdResource.Body.toString());

                  const accept = event.headers.Accept;
                  if (networkHeaders.indexOf(accept) !== -1) {
                      const networkHeader = accept.substring('application/'.length);
                      const network = networkHeader.substring(0, networkHeader.indexOf('-'));
                      const environment = networkHeader.substring(network.length + 1, networkHeader.indexOf('+'));
                      const selectedAddress = payIdJson.addresses
                          .find(a => a.paymentNetwork === network.toUpperCase() && a.environment === environment.toUpperCase());
                      if (selectedAddress) {
                          return { ...success, body: JSON.stringify(selectedAddress) };
                      }
                      return {
                          statusCode: 404,
                          body: `No address for ${accept} available for PayID ${payId}`,
                      };
                  }
                  return { ...success, body: JSON.stringify(payIdJson) };
              } catch (error) {
                  console.log(error);
                  const response = {
                      statusCode: 404,
                      body: 'PayID resource not found',
                  };
                  return response;
              }
          };
      Description: "PayID Server"
      Environment:
        Variables:
          PAYID_BUCKET: !Ref "s3Bucket"
      FunctionName: !Ref "lambdaFunctionName"
      Handler: "index.handler"
      MemorySize: 128
      Role: !GetAtt "lambdaIAMRole.Arn"
      Runtime: "nodejs12.x"
      Timeout: 10

  lambdaApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !GetAtt "lambdaFunction.Arn"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${apiGateway}/*/GET/"

  lambdaApiGatewayPayIdResourceInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !GetAtt "lambdaFunction.Arn"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${apiGateway}/*/GET/*"

  lambdaIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Effect: "Allow"
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${lambdaFunctionName}:*"
          PolicyName: "payid-server-logs"
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - "s3:*"
                Effect: "Allow"
                Resource:
                  - "*"
          PolicyName: "payid-server-s3"


  lambdaLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/aws/lambda/${lambdaFunctionName}"
      RetentionInDays: 90

  hostedZone:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: !Ref "domainName"

  dnsForHostedZone:
    Type: "AWS::Route53::RecordSetGroup"
    Properties:
      HostedZoneId: !Ref "hostedZone"
      RecordSets:
        - Name: !Sub "${domainName}."
          Type: "A"
          AliasTarget:
            DNSName: !GetAtt "apiGatewayCustomDomain.DistributionDomainName"
            HostedZoneId: !GetAtt "apiGatewayCustomDomain.DistributionHostedZoneId"

Outputs:
  apiGatewayBaseURL:
    Value: !Sub "https://${apiGateway}.execute-api.${AWS::Region}.amazonaws.com/"

  apiGatewayInvokeURL:
    Value: !Sub "https://${apiGateway}.execute-api.${AWS::Region}.amazonaws.com/release"

  lambdaArn:
    Value: !GetAtt "lambdaFunction.Arn"